### PR TITLE
Added some getters to handle RGBA as int and RGB / RGBA packed ints.

### PR DESCRIPTION
**Pull request by darkhax**
`getRed()` Gets the red as an integer. 0-255
`getBlue()` Gets the blue as an integer. 0-255
`getGreen()` Gets the green as an integer. 0-255
`getAlpha()` Gets the alpha as an integer. 0-255
`getRGB()` Gets the RGB as a packed integer.
`getRGBA()` Gets the RGBA as a packed integer.

### CODE REVIEW

**Comment by sriharshachilakapati** [comment]
Cool, but the code for RGB construction is not right I believe. It should be `(red << 24 | green << 16 | blue << 8 | 255)`. Alpha is 255 in RGB

**Comment by darkhax** [comment]
Okay, I have changed getRGB to include the alpha component at 255.

**Comment by sriharshachilakapati** [comment]
What does the `calculateDamage` method do?

**Comment by darkhax** [comment]
LOL, nice catch. It's just a rough example for showing @lclc98 something. I didn't expect to have to commit again, and forgot to remove the method from the file x)

**Pull request merged**
