### PR TITLE
Added better Logger functionality

### PR DESCRIPTION
**Pull request by Gamefreak0**
Customizable time stamp format
Changed log, warn, and error methods to require Object instead of String
Added Documentation

### CODE REVIEW

**Comment by sriharshachilakapati** [comment]
Thanks for contributing @Gamefreak0

**Comment by sriharshachilakapati** [comment]
I want to add your name to the author list in the javadoc of this class. Should I refer you as @Gamefreak0 or do you want to have your real name there?

**Comment by Gamefreak0** [comment]
Thanks, just refer to me as Gamefreak0

**Comment by sriharshachilakapati** [comment]
@Gamefreak0 

Okay, I'll add that in the next commit. By the way, can you get on to the IRC, I have a few questions to ask you, but GitHub isn't a place for that. The channel is [**#SilenceEngine**](https://kiwiirc.com/client/irc.freenode.net/#SilenceEngine) on Freenode.net

Hoping to see you there. Thanks again.

**Pull request merged**
