### PR TITLE
Basic code cleanup/update

### PR DESCRIPTION
**Pull request by ShadowLordAlpha**
Basic code cleanup such as adding serial UIDs to classes and removing unused imports as well as marking an unused method in a private class to
see if we should just remove it

### CODE REVIEW

**Comment by sriharshachilakapati** [comment]
Why add `serialVersionUID` fields to these classes? They are only required for classes which implement the `Serializable` interface, but in our case, we cannot serialize OpenAL and OpenGL classes. I don't get the point in adding them. Could you please clarify why you added them?

**Comment by ShadowLordAlpha** [comment]
`Throwable` implements `Serializable` so `Exception` implements it as well and so adding the UID is just to make `Serializable` work properly even if the engine itself does not directly use it.

**Comment by sriharshachilakapati** [comment]
I really don't see where people serialize exceptions, that is an extremely rare case. But I don't think there is any wrong in this, I will merge this request. Thanks.

**Comment by ShadowLordAlpha** [comment]
it helps sometimes because if an `Exception` is thrown the whole exception can be sent to the dev or if it occurred server side to the user. Most people will probably never use nor need it however if someone does use it and we don't have the UID and the version changes it could break their code if they are storing the exceptions ect... (mostly it was giving me warnings in eclipse and its better to specify it and not need it than to need it and not have it)

**Pull request merged**
