### PR TITLE
Documenting/Updating GLFW classes

### PR DESCRIPTION
**Pull request by ShadowLordAlpha**
~~Documenting all of the `GammaRamp` class~~
Documenting all of the `VideoMode` class
Added Constructor that can parse a `ByteBuffer` to `VideoMode`
Changed setter type Methods in `VideoMode` to deprecated and commented out the code within those methods

### CODE REVIEW

**Comment by ShadowLordAlpha** [comment]
well GammaRamp is outdated -_-

**Comment by ShadowLordAlpha** [comment]
There we go

**Comment by sriharshachilakapati** [comment]
I had the same changes, except that I removed the setters entirely instead of deprecating them. This class is written in 0.0.3a and since this is still the current version, there is no need to deprecate the functionality.

Also, your code style is different to the style used in this project. Will you please use the style of the repo here? I can attach the formatter settings for you. The link is here: https://silenceengine.slack.com/files/shc/F04LL3FT0/silenceengine.xml

**Comment by sriharshachilakapati** [comment]
I'll be merging this manually.

**Pull request closed without merging**
