### PR TITLE
Update to TrueTypeFont

### PR DESCRIPTION
**Pull request by ShadowLordAlpha**
A small update to your bug fix 76a08793fb893a8806c1ea6a3342955ef2b3a5ff that allows it to skip if the string is nothing but whitespace as well as remove all extra whitespace on the end of the string. This is a better solution than what I was talking about as it lets formatting whitespace stay but still has a possible performance boost by removing trailing whitespace at the same time as formatting for the empty string check so that strings of nothing but whitespace also trigger the check.

Extra parts in the gradle files allow for eclipse to also be used using the `eclipse build` command and then importing the project into an eclipse workspace and adds the extra files to the .gitignore file.

### CODE REVIEW

**Comment by ShadowLordAlpha** [comment]
sorry about the extra junk commits -_- they were not supposed to get synced over but i forgot all about them

**Comment by sriharshachilakapati** [comment]
I can only merge if you add your name to the credits in the changed files. Please add `@author yourPreferredName` to the documentation on all the changed files.

**Comment by ShadowLordAlpha** [comment]
`@author` tag added to the one code file I changed

**Comment by sriharshachilakapati** [comment]
Thanks!

**Comment by sriharshachilakapati** [comment]
BTW, can you join the IRC? It's #SilenceEngine on Freenode. I have a few things to talk with you, and GitHub is not meant for that.

https://kiwiirc.com/client/irc.freenode.net/#SilenceEngine

**Comment by ShadowLordAlpha** [comment]
ya i saw that :p

**Pull request merged**
